name: ckb-auth-integration-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Cache of Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.os }}-${{ runner.os }}-${{ runner.arch }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-${{ runner.os }}-${{ runner.arch }}-cargo-build

    - name: Install ckb-auth-cli
      run: make prepare

    - name: Run tests
      run: make testAll

    - name: Publish reports
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: jfoa-build-reports-${{ runner.os }}
        path: /home/runner/work/ckb-auth-integration-test/ckb-auth-integration-test/testcases/report