name: ckb-auth-integration-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Rust Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install ckb-auth-cli
      run: make prepare

    - name: Run tests
      run: make testAll

    - name: Publish reports
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: jfoa-build-reports-${{ runner.os }}
        path: /home/runner/work/ckb-auth-integration-test/ckb-auth-integration-test/testcases/report